version: "3"

x-logging:
  &loki-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "10"
    tag: "{{.ImageName}}|{{.Name}}"

services:
  app_python:
    image: tonydecva180xn/devops:lab-3
    ports:
      - 5000:5000
    logging: *loki-logging
    networks: [apps]

  loki:
    image: grafana/loki:2.6.1
    volumes:
      - loki-data:/tmp/loki/
    networks: [monitoring]
    command: -config.file=/etc/loki/local-config.yaml
    logging: *loki-logging

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ./configs/promtail.yml:/etc/promtail/config.yml
    networks: [monitoring, apps]
    command: -config.file=/etc/promtail/config.yml
    logging: *loki-logging

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/datasources:/etc/grafana/provisioning/datasources
    networks: [monitoring]
    logging: *loki-logging

volumes:
  grafana-data: {}
  loki-data: {}
  promtail-data: {}

networks:
  monitoring: {}
  apps: {}
