hello: ENC[AES256_GCM,data:xDCeGNm+GhjqwVzHA2VLUhdKkVPu5YtpQu5srx1AlkgWGcBeWko6m6hoawvA6Q==,iv:6TvhR4Mp7hi0gVFJn04jJaS9/M082WaTWByjYYSxRTE=,tag:rzmuNuVckkAauI/D650kjA==,type:str]
example_key: ENC[AES256_GCM,data:2ab2NzdKa20APkY4zQ==,iv:bJOihpldnyQAxoayPIzUGAvKFThDa/E+5Ahx2jI/Dxs=,tag:yRucu/vCoDM4qhi2jVCDwQ==,type:str]
#ENC[AES256_GCM,data:maOyLzE/PcFQ4ElQuCaEBw==,iv:Iox9soWfFnzsjSXztKGmq94Kkstv1TKIy5I/fCc6rtQ=,tag:43SjXUo/jMISuQQuL+AIrg==,type:comment]
example_array:
    - ENC[AES256_GCM,data:bEucxPS7bsSJnR1qHl4=,iv:dgodrhgBndyuQ64QsWOCYOCTlxRo6EVp8u6XKMGIADw=,tag:zC12a6GR9NUyYVvr8+BJ/Q==,type:str]
    - ENC[AES256_GCM,data:LBU5WQDQ/sJvXgnJRVM=,iv:9YJuaWx6Tru9DRRkutt2CC+0NhNi+U9KV/HpcmZpiXs=,tag:H2gD2ZX/PKKDvnc/M95GXQ==,type:str]
example_number: ENC[AES256_GCM,data:MOTo7DEhifVKzw==,iv:nHC3Oj7Gz/DeVVaKzyJdeg2MNr0++XB+vKXTI3/+4ls=,tag:+W2rhFDAmiGvuDB80LlqfQ==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:DA1uzA==,iv:IT08NoU9FG4H8YnDKrxXCc9JhAEq2eolguLI8hmBZcQ=,tag:8tdT3id2fIuNBRAQ/hTw0Q==,type:bool]
    - ENC[AES256_GCM,data:XcUNpkk=,iv:Gkmp787ciLIGIvFxBy//NqCC7i+CvUkL80qibg9SJdY=,tag:q2H4KL7w2Dlqv3Pi1MeTcw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-19T16:59:45Z"
    mac: ENC[AES256_GCM,data:v/4zxsm1M4CaIegSXrdlRj59T6CgoxzUOxKP+G2zaSrrdA8i5OPNO8lwQ0xrk/PfRGmmBQUsyT3+UO+4IVNwxdkyz+B/JKPPRXkwPPn3avraxUROaycrSLUEQE33EevnV0Zaexb4CdTeI3bv6Zl3CJ3APsWERfxTxqOk4wFhjbw=,iv:dpvsMtlAiLO4AKgwU1Oc2mJYP79ch3iRVWbXxo3uYoo=,tag:Wi8ICtWBg9GnYXqJEr1n6g==,type:str]
    pgp:
        - created_at: "2023-02-19T16:59:07Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhF4DbXBt/3+tmTUSAQdAFbRnapOMZeympfI3T2rumPFdVt858xby7qHwmoN+gDIw\r\ngC/1KxRRe5kI5xZsokFmnI5tdoKkNZqAjV6BVHasp2Fkxxw6GI+/uPdJJ4inIjAA\r\n1GgBCQIQUNkxWZCmg41ot+g2TCr4m+5Aqxm01AZQ7bSieZCm5DeB/ouyCCBei/ra\r\nqYdhz3CVFAQdvim9xYPKd7BC5sGNlzrhVmt0nc6XkaQm0izoODC0q5n+edkrhIeZ\r\naSQsVDUofno96A==\r\n=VBxQ\r\n-----END PGP MESSAGE-----\r\n"
          fp: 109FB2B55A117967519A8C9FBE8D4A37526B2C59
    unencrypted_suffix: _unencrypted
    version: 3.7.3
